### ISSUE TITLE
Stuck during installation on macOS for more than n hours

### ISSUE THREAD

**Issue by n-WN** [passagemath/passagemath#327]
### Environment

- **OS**: macOS 14.7
- **Sage Version**: 10.4

### Steps To Reproduce

```shell
python3 -m pip install -v passagemath-conf.log
```

### Config log

[python3 -m pip install -v passagemath-conf.log](https://github.com/user-attachments/files/17671354/python3.-m.pip.install.-v.passagemath-conf.log)

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment]
```
    [gfan-0.6.2.p1]   Attempting to download package gfan0.6.2.tar.gz from mirrors
    [gfan-0.6.2.p1]   https://github.com/passagemath/passagemath/releases/download/passagemath-10.4.47/gfan0.6.2.tar.gz
    [gfan-0.6.2.p1]   [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
    [gfan-0.6.2.p1]   ERROR [transfer|run:135]: [Errno socket error] [Errno 60] Operation timed out
```

This looks like just a temporary internet connectivity problem...

**Comment by mkoeppe** [comment]
In #328 I now set up a shared download directory so that the whole downloading will not start from scratch with every new version tried
