### ISSUE TITLE
ccache install broken since upgrade to 4.10.2

### ISSUE THREAD

**Issue by mkoeppe** [passagemath/passagemath#613]
Since https://github.com/sagemath/sage/pull/39119, ccache cannot be installed because it tries to download xxhash at install time. @gmou3 @kwankyu @vbraun 

https://github.com/passagemath/passagemath/actions/runs/12532079587/job/34950722473#step:11:2642
```
  [ccache-4.10.2]   [spkg-install] -- Using src='https://github.com/Cyan4973/xxhash/archive/refs/tags/v0.8.2.tar.gz'
  [ccache-4.10.2]   [spkg-install] -- Retrying...
  [ccache-4.10.2]   [spkg-install] -- Using src='https://github.com/Cyan4973/xxhash/archive/refs/tags/v0.8.2.tar.gz'
  [ccache-4.10.2]   [spkg-install] -- Retry after 5 seconds (attempt #2) ...
  [ccache-4.10.2]   [spkg-install] -- Using src='https://github.com/Cyan4973/xxhash/archive/refs/tags/v0.8.2.tar.gz'
  [ccache-4.10.2]   [spkg-install] -- Retry after 5 seconds (attempt #3) ...
  [ccache-4.10.2]   [spkg-install] -- Using src='https://github.com/Cyan4973/xxhash/archive/refs/tags/v0.8.2.tar.gz'
  [ccache-4.10.2]   [spkg-install] -- Retry after 15 seconds (attempt #4) ...
  [ccache-4.10.2]   [spkg-install] -- Using src='https://github.com/Cyan4973/xxhash/archive/refs/tags/v0.8.2.tar.gz'
  [ccache-4.10.2]   [spkg-install] -- Retry after 60 seconds (attempt #5) ...
  [ccache-4.10.2]   [spkg-install] -- Using src='https://github.com/Cyan4973/xxhash/archive/refs/tags/v0.8.2.tar.gz'
  [ccache-4.10.2]   [spkg-install] CMake Error at xxhash-subbuild/xxhash-populate-prefix/src/xxhash-populate-stamp/download-xxhash-populate.cmake:163 (message):
  [ccache-4.10.2]   [spkg-install]   Each download failed!
  [ccache-4.10.2]   [spkg-install] 
  [ccache-4.10.2]   [spkg-install]     error: downloading 'https://github.com/Cyan4973/xxhash/archive/refs/tags/v0.8.2.tar.gz' failed
  [ccache-4.10.2]   [spkg-install]           status_code: 28
  [ccache-4.10.2]   [spkg-install]           status_string: "Timeout was reached"
  [ccache-4.10.2]   [spkg-install]           log:
  [ccache-4.10.2]   [spkg-install]           --- LOG BEGIN ---
  [ccache-4.10.2]   [spkg-install]           Uses proxy env variable https_proxy == 'http://192.0.2.0:5187/'
  [ccache-4.10.2]   [spkg-install]     Trying 192.0.2.0:5187...
```

**Comment by kwankyu** [comment]
Hi

xxhash is a dependency of ccache according to https://github.com/ccache/ccache/blob/master/doc/INSTALL.md

Why did it fail to download xxhash? No internet connection?

Creating a new xxhash spkg and making it an "order-only" dependency for ccache would be a solution?

**Comment by mkoeppe** [comment]
Hi @kwankyu, "normal" packages are not allowed to download stuff. To enforce this rule, the build system poisons the `http_proxy` variable.

> Creating a new xxhash spkg and making it an "order-only" dependency for ccache would be a solution?

Yes

**Comment by gmou3** [comment]
It seems that in order to add `ccache` properly one must also add `hiredis`, `xxhash`, and `zstd`. (For the PR I disabled `hiredis` and wrongly assumed that the rest are too basic not to be included in the system.) Isn't that too much bloat for the `spkg`s collection? Or should I go ahead and add all of them?

**Comment by kwankyu** [comment]
That is already what happened with the jupyter spkg... This is a consequence of the doctrine

> "normal" packages are not allowed to download stuff.

which I believe should be abolished.

**Comment by mkoeppe** [comment]
FWIW, in passagemath I have relaxed this rule already for optional packages, to simplify adding the macaulay2 package.
